### ISSUE TITLE
Outdated data

### ISSUE THREAD

**Issue by sevastos** [duckduckgo/zeroclickinfo-fathead#115]
I was checking out the fathead IAs and noticed on the [docs](https://duck.co/duckduckhack/fathead_overview) the following part:
> and if necessary, will be run periodically to keep the database current

However, I couldn't find details on how to instruct this, I checked some existing fathead IAs and I assume they are not specified on meta.txt or .pm, but you maybe add a cron on per-case basis?
In any case, it would help to clarify this at the docs.

Lastly, I did a search using the Airport fathead, for a new airport that [was added on Sept 2014](http://en.wikipedia.org/w/index.php?title=List_of_airports_by_IATA_code%3A_A&diff=624214924&oldid=612241554) and it seems absent from the index: https://duckduckgo.com/?q=airport+AHJ obviously the same case could be for other IAs.

**Comment by moollaza** [comment]
@sevastos for now we've been updating the fatheads as needed. Usually when someone let's us know it's out of date, we tend to update it :)

I like the idea of indicating how often it should be updated though. I'll mention this to the team because its a problem that we don't have a great solution for.

**Comment by jdorweiler** [comment]
Ran into an error with the airport code parser. https://github.com/duckduckgo/zeroclickinfo-fathead/issues/123

**Comment by jdorweiler** [comment]
Fixed!
https://duckduckgo.com/?q=airport+AHJ&ia=about
