### ISSUE TITLE
ISO3166Codes is broken; Needs new source URL

### ISSUE THREAD

**Issue by iambibhas** [duckduckgo/zeroclickinfo-fathead#127]
Seems like the source url mentioned in the [data.url](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/share/fathead/iso_3166_codes/data.url) file is broken - http://www.iso.org/iso/list-en1-semic-3.txt

Tried searching for `us iso` and `iso tk` as mentioned in the [fathead script](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/lib/DDG/Fathead/ISO3166Codes.pm), not working.

**Comment by moollaza** [comment]
@pfirsichbluete would you be interested in fixing up this Fathead? It looks like the URL originally used to download the data no longer exists!

**Comment by pfirsichbluete** [comment]
@moollaza I touched this fathead only once, when mass-updating the code urls. So I have no clue about
the inner workings here.

I had a brief look nonetheless.

Some copies of the file can be found on the net.
E.g.:
* https://raw.githubusercontent.com/vandrijevik/iso3166/f98486e42183828490e122d216ef08a934b8bd36/lib/iso3166/list-en1-semic-3.txt
* http://sermad.soup.io/post/18530218/http-www-iso-org-iso-list-en1?sessid=cef01b272dd3ac45c1065357f7ed0c02

but as ISO took the file offline (see below), I am not sure how current those are or how often they will get updates, and more importantly, I am not sure how legally sound it is to use those. (If you end up using any of those, make sure you respect the encoding. “Côte d'Ivoire” and “Curaçao” can serve as test examples)

ISO itself moved the public country codes to their Online Browsing Platform at https://www.iso.org/obp/ui/#search/code/
That Online Browsing Platform exposes the data only in a paged list, needs CSRF tokens, sessions and what not. So both fetching and parsing would have to be redone.

But if one would be redoing fetching and parsing, it might be worth jumping on [Wikipedia's rendition of it](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements), as those would allow to provide with good links to further information about the country itself.
(IIRC the `airports` fathead already parses a Wiki table using BeautifulSoup, so there is already code how to do that)

So we're left with 1 option that is not obviously legally sound, and 2 options that need to redo the fathead. Since, I am not invested in this fathead, and I won't find time the next few weeks to work on it, maybe someone from Global Quack & Hack participant may want to grab it?
