### ISSUE TITLE
Wookieepedia: triggered when searching for definition

### ISSUE THREAD

**Issue by scottmacpherson** [duckduckgo/zeroclickinfo-fathead#176]
### Reproduce issue

https://duckduckgo.com/?q=vindictive

### Expected result

    <title>vindictive at DuckDuckGo</title>

### Actual result

    <title>vindictive (Star Wars) at DuckDuckGo</title>

Page source contains references to `DDG::Fathead::Wookieepedia`, but apart from the title the rendered page looks like a normal word definition IA.

I can't find any reference to "Star Wars" or "vindictive" in this repository.

![2016-01-11_10-17-28](https://cloud.githubusercontent.com/assets/1926760/12224778/a63f2c3e-b84c-11e5-92ca-f580364e5fd5.png)

------
IA Page:  http://duck.co/ia/view/wookieepedia

**Comment by moollaza** [comment]
@scottmacpherson thanks for reporting. The Wookiepedia Fathead is a closed source one so there's no code here related to it.

It looks like there's no Wikipedia articles related to this, which is why Wookipedia is showing, but I'm glad that we're showing the definition as the default tab.

@jdorweiler @mrshu can we prevent Wookiepedia from triggering on dictionary words? should we consider this tolerated?

**Comment by jdorweiler** [comment]
Seems like it has been fixed?
