### ISSUE TITLE
Wikipedia: does not take into account locale

### ISSUE THREAD

**Issue by halosbe** [duckduckgo/zeroclickinfo-fathead#189]
Region is set to Belgium (language = Dutch). Wikipedia instant answer always shows me English page. First result in regular search results is the Dutch version I would expect. Screenshot attached.
Thanks.

![schermafbeelding 2016-03-13 om 09 16 01](https://cloud.githubusercontent.com/assets/12977828/13727683/d7bcde88-e8fc-11e5-8246-9ee8af6f0aca.png)

---

IA Page:  http://duck.co/ia/view/wikipedia_fathead 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @duckduckgo

**Comment by tagawa** [comment]
Thanks for reporting @halosbe. I actually get English for both the Wikipedia entry and search results (with Belgium-nl selected). Anyway, @mrshu might know if it's possible to get localised Wikipedia displaying.

**Comment by mrshu** [comment]
Thanks @halosbe and @tagawa.

It turns out that this is a localized issue with just the example @halosbe pointed out. I can trigger Dutch Wikipedia for other queries, such as [Alan Turing](https://duckduckgo.com/?q=alan+turing&kad=nl_BE&ia=about) and also the (I suppose) Dutch name of the flower in your query [Knoopkruid](https://duckduckgo.com/?q=Knoopkruid&kad=nl_BE&ia=about).

The fact that I can reproduce what you are seeing suggests that there is certainly an issue. I'll take a look and will keep you posted for sure.
