### ISSUE TITLE
MDN JavaScript: use Wget to fetch data

### ISSUE THREAD

**Issue by MariagraziaAlastra** [duckduckgo/zeroclickinfo-fathead#256]
Currently MDN JS uses [a custom method](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/lib/fathead/mdnjs/fetch.py) to fetch the data, and it's taking too long to execute (wasn't finished after about 40 minutes on my machine).

Wget should be faster and easier, let's just use that and fetch:
- https://developer.mozilla.org/en-US/docs/Web/JavaScript 
- https://developer.mozilla.org/en-US/docs/Web/API

Read the docs to learn more about [Fatheads](http://docs.duckduckhack.com/resources/fathead-overview.html).

Please see the forum topic [Improve MDN JavaScript Fathead](https://forum.duckduckhack.com/t/improve-mdn-javascript-fathead/155) for more details.
Thanks!

-----------------------------------------------
IA Page: https://duck.co/ia/view/mdnjs
Maintainer: @ericedens 

Forum topic: [Improve MDN JavaScript Fathead](https://forum.duckduckhack.com/t/improve-mdn-javascript-fathead/155)

This issue is part of the [Programming Mission](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53): help us improve the results for [JavaScript related searches](https://forum.duckduckhack.com/t/javascript-search-overview/94)!

**Comment by bfmags** [comment]
Like original python script, it was taking 30 minutes to download 4011 pages (from the 15294 urls existing in sitemap.xml).

A solution would be using xargs for parallel download but it's tricky since it has custom output filename. This version using unattended background downloads, and it was pretty fast, but the processor usage is huge. WIP

https://github.com/bfmags/zeroclickinfo-fathead/blob/bfmags/mdnjs/lib/fathead/mdnjs/fetch.sh

**Comment by ericedens** [comment]
Have you guys tried modifying the 'sleep' parameter to make it go faster?
It appears to be set y

**Comment by ericedens** [comment]
... It appears to be set to 5 seconds, which is to avoid overloading their
servers. At one request per second, which is probably what you'll get
single threaded without sleeping, you'll get 3600 pages per hour.

Have you considered contacting Mozilla to see if they'll provide an API? Or
a database dump? That would be less fragile, and allow you to spend more
time crafting nice search results instead of maintaining this one-off
crawler / parser. Also, it will conserve their server resources. So it's a
win-win.

**Comment by bfmags** [comment]
@ericedens thanks for the suggestion, that's definitely something to consider

**Comment by MariagraziaAlastra** [comment]
@bfmags can you open a PR to this repo?
Anyway I tried it and it gives me this error: 
<pre>fetch.sh: 23: fetch.sh: Syntax error: "(" unexpected (expecting "}")</pre>

Looks like it's [this line](https://github.com/bfmags/zeroclickinfo-fathead/blob/bfmags/mdnjs/lib/fathead/mdnjs/fetch.sh#L23)

@ericedens Thanks for the suggestion!

**Comment by bfmags** [comment]
PR done! https://github.com/duckduckgo/zeroclickinfo-fathead/pull/268

**Comment by bfmags** [comment]
@MariagraziaAlastra

 I'm not getting that error. If running Debian based OS, using command sh it will use dash instead of bash, and sometimes can cause errors

>  ./fetch.sh

**Comment by moollaza** [comment]
Fixed in #268
