### ISSUE TITLE
Automated tests against output.txt for PRs?

### ISSUE THREAD

**Issue by jrasanen** [duckduckgo/zeroclickinfo-fathead#264]
Hi,

would it be possible to write some sort of unit-tests against the output.txt tsv-file and automate Travis (or equivalent) to do sanity check for each commit in PRs?

Doing automated testing would improve the quality of results and lessen the burden for maintainers/code reviewers.

I am not yet that familiar with what the actual tests could be, but couple ones I could think of:
- Sanity checks for texts (no unnecessary leading newlines )
- Check for "R" entries whether the referenced key exists
- Try to catch all 404's / dead links

Any opinions or comments for this suggestion?

**Comment by jdorweiler** [comment]
@moollaza might be useful to add this into duckpan?

**Comment by sahildua2305** [comment]
@jrasanen This is a great idea, indeed! :smile:

**Comment by jdorweiler** [comment]
Seems like a good idea to me. A few things to consider:
- stick with perl and [prove](http://perldoc.perl.org/prove.html) to be consistent with the other repos
- not every PR will have an output.txt file and it's okay if it doesn't
- To avoid testing large files maybe set an upper limit on the number of entries to test

**Comment by moollaza** [comment]
@jrasanen @jdorweiler yeah this sounds pretty do-able.

If you use `DBD::CSV` like I have to read the output.txt into a DB it may help to confirm the redirects have valid keys, but if we assume redirects are always defined after the article that may not be necessary.

I think that checking for 404's should be a special opt-in check because I imagine that will make the tests very lengthy.

@jrasanen is this something you'd like to implement?

**Comment by sahildua2305** [comment]
@moollaza This sounds good. I'd like to implement it in case @jrasanen doesn't take it up. :smile:

**Comment by moollaza** [comment]
If we want these tests to be run for each PR by Travis, then they'll need to be implemented in the Fathead directory.

If we just want this as a DuckPAN feature, then we'll need to implement some new functionality into the `duckpan test` command.

The former sounds ideal so that future PRs should be guaranteed not to break anything in the output.txt

**Comment by sahildua2305** [comment]
Both things should be there. Travis integration should be preferred however. Because that will make PR reviewing very easy.

**Comment by sahildua2305** [comment]
Any update on this, @jrasanen @moollaza  ?

**Comment by moollaza** [comment]
@sahildua2305 there's no one working on it that I'm aware of

**Comment by pjhampton** [comment]
As we've moved away from the programming mission, I will close this for now. We can reopen once we come back to Fathead type IAs 👍  😄
