### ISSUE TITLE
'Category' vs 'Related'

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/zeroclickinfo-fathead#286]
In the docs it says:

> Related topics. These will be turned into links in the Zero-click Info box. Examples: [[Perl Data Language]]. If the link name is different, [[Perl Data Language|PDL]].

And

> Categories. An article can have multiple categories, and category pages will be created automatically. An example of a category page can be seen at http://duckduckgo.com/c/Procedural_programming_languages. Multiple categories must be separated by an escaped newline, \n. Categories should generally end with a plural noun. Examples: Procedural programming languages\n

But this doesn't seem to be the case. On Beta 'related' topics are not shown for the `related` field, but it seems that instead anything in `categories` is displayed in the infobox under `Related Topics`:

![screenshot-2016-08-03-11 50 57_420_128](https://cloud.githubusercontent.com/assets/8598426/17363119/938782ce-5970-11e6-8dcc-1e23be88062a.png)

I find this behavior somewhat confusing. @moollaza what is the correct approach to related topics? E.g. related variables or functions? It seems a bit off putting them into `categories`.

cc @duckduckgo/community-leaders

**Comment by moollaza** [comment]
Whatever is on Beta is "correct". I was digging through our source code to simulate how Fatheads work in DuckPAN and I probably made a few mistakes because I'm not familiar with the entire Fathead codebase (which is large, and old).

Until recently, I hadn't been too familiar with Fatheads at all (Jason and Jag have been managing them) so I think I got confused here.

I now realize that "categories" are just used internally to generate category pages, which are similar to a disambiguation view, but instead shows a grouping of all articles with the same category.

Related Topics are meant to be displayed as links in the infobox, which link to a DDG search for the named related topics (meant to be other Fathead Articles)

**Comment by GuiltyDolphin** [comment]
@moollaza Currently there aren't any category pages or infoboxes in the DuckPAN implementation; this is all on Beta.

My intuition was that anything in the same category would be put in a disambiguation/meanings page when searching for that category, and the 'related topics' would appear in the infobox (which doesn't appear to be the case).

Instead, categories are displayed in the infobox, and related topics seem to have no effect; perhaps this is a bug?

cc @jdorweiler (we've been discussing some... Oddities with categories).
