### ISSUE TITLE
Fathead parse.sh scripts should alpha-sort output.txt

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-fathead#326]
Currently, the ordering of most output.txt files is random, and in some cases, subsequent runs of `parse.sh` produce a differently ordered file.

This is currently the case for the MDN CSS Fathead, which means when the parser is modifed and a new output.txt file is generated, its hard to determine what changes are due to the code changes, and which are just a re-ordering of existing articles.

By sorting the output.txt file, it will be easier to read, and will ensure that only new/remove/modified content will appear in the git diff.

**Comment by moollaza** [comment]
As a simple fix, I've updated the MDN Fathead's parse.sh script to use `sort output.txt -o output.txt`

If/when we standardize the Fathead "build" process, this should be handled by that instead of the individual Fathead parsing scripts.

**Comment by GuiltyDolphin** [comment]
@moollaza I'm not entirely sure why you would need to inspect the `output.txt` that much, you can just use `duckpan query` to see the field information. But I guess it could be better to have some ordering.

We should definitely wait for the utility packages before we go ahead with this - otherwise we will just have more work to do when converting existing FatHeads over.

**Comment by preemeijer** [comment]
Hello, is this still an open issue? That could be worked on?
Cheers, Paul

**Comment by moollaza** [comment]
@preemeijer I've partially fixed this for now by appending `sort` to the parse.sh scripts -- there are probably a few more that can be manually updated, but we don't really have a robust solution right now..
