### ISSUE TITLE
C++ Reference Docs: Switch to use new Fathead Template Elements

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-fathead#407]
We now have [Fathead Template Elements](https://docs.duckduckhack.com/resources/fathead-overview.html#formatting-the-abstract) designed specifically for Programming Fatheads. These are HTML elements that should be added to the output.txt by each Programming Fathead's parsing script(s).

This Fathead should be updated to use the templates:
- The entire abstract should be wrapped in a `<div>` with class `prog__container`
- Any text before/after the code blocks must be wrapped in `<p>` tags
- Any subheadings should be wrapped in a `<div>` with class `prog__sub`

Here is an example:

``` html
<section class="prog__container">
    <p>Creates a JavaScript Date instance that represents a single moment in time.</p>
    <pre>
        <code>
            new Date;
            new Date(value);
            new Date(dateString);
            new Date(year, month[, day[, hour[, minutes[, seconds[, milliseconds]]]]]);
        </code>
    </pre>
    <span class="prog__sub">Return Value</span>
    <p>The removed element.</p>
</section>
```

---

This issue is part of the [Programming Mission](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53): help us improve the results for [C++ related searches](https://forum.duckduckhack.com/t/https://forum.duckduckhack.com/c/programming/66-category)!

---

IA Page:  http://duck.co/ia/view/cppreference_doc 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @ManrajGrover

**Comment by sahildua2305** [comment]
I'll push PR for this later today.

**Comment by sergey-krusch** [comment]
The way it is organized currently is: the data generation script for DDG is actually hosted on cppreference.com. I assume that this is a known and a preferred way of organizing this. If not, then... it needs to be changed :)
Anyway, I have a fix. But because it requires several steps (make a commit to the cppreference.com repo and then wait for it to appear in the cppreference.com archives) I'd like someone to verify the format.
Example (ignore indentation, it is for readability only):
```html
<section class="prog__container">
  <p>Computes the sum of the given value <code>init</code> and the elements in the range <code>[first, last)</code>.</p>
  <pre>
    <code>
      template&lt; class InputIt, class T &gt;\nT accumulate( InputIt first, InputIt last, T init );
    </code>
  </pre>
  <pre>
    <code>
      template&lt; class InputIt, class T, class BinaryOperation &gt;T accumulate( InputIt first, InputIt last, T init,\n              BinaryOperation op );
    </code>
  </pre>
</section>
```

**Comment by sergey-krusch** [comment]
@sahildua2305 Yeah, I've seen it. But the issue seems to be referring to the cppreference_doc specifically. Though this is something that needs clarification as well.

**Comment by sahildua2305** [comment]
@moollaza can you please confirm?

**Comment by moollaza** [comment]
@sahildua2305 @sergey-krusch I happened to [discuss this on the Forum](https://forum.duckduckhack.com/t/create-ia-fathead-for-c-library-functions/1042/23?u=moollaza) yesterday :)

The cppreference_doc Fathead is extremely old and needs to be rebuilt. @sergey-krusch I was not aware that cppreference.com had an open-source repo though -- does it house the code that is being passed along to us in the tarball?

If that code is open, then I suppose we could update it accordingly, bit really I think we should rebuild this IA to function as all the others do, which means housing the parsing code in our Fathead repo, so we can update it as necessary, without depending on a third part to manage and release the changes. We can still download the XML to be parsed from cppreference.com if they prefer that over scraping their site.

I

**Comment by moollaza** [comment]
@sahildua2305 @sergey-krusch the other code in the `c++_ref` should be removed from the repo, or adapted for this IA. Either way, the code used for the IA with ID `cppreference_doc` needs to live in the `cppreference_doc` directory 👍

**Comment by p12tic** [comment]
Hi,

I'm the original author of the cppreference_doc fathead plugin code. This issue was only recently brought to light to me. If it's still possible, I would like to volunteer implementing needed fixes for it. However, I would strongly recommend against spliting the output.txt generation code from the cppreference repository. I wrote a much longer comment with justification in https://github.com/duckduckgo/zeroclickinfo-fathead/pull/539#issuecomment-259821640.

**Comment by rasikapohankar** [comment]
@sahildua2305 we can update the parsing script in the [cppreference-doc repository](https://github.com/p12tic/cppreference-doc) by sending a PR there. What would you like to do?

**Comment by sahildua2305** [comment]
Can you do it, @rasikapohankar ?

**Comment by p12tic** [comment]
@sahildua2305 Are you still interested in improving this Fathead? If not, I can take over.

**Comment by sahildua2305** [comment]
@p12tic please go ahead 😄

**Comment by p12tic** [comment]
It looks like simple fix @sergey-krusch (https://github.com/p12tic/cppreference-doc/commit/7352ebdbb5c35b393b41a8395193e87a1876d401) has been actually enough to solve this specific issue. I've merged that to cppreference-doc repo and additionally did some extra stuff :-)
 - refactored the code generating output.txt
 - merged code snippets into single code block so that it's less confusing
 - added command-line config options so that it's possible to somewhat configure the output.txt generation from parse.sh in this repository

I have output.txt that I would like to test: https://gist.github.com/p12tic/87488c7d68715b267100b3b69de46005. Could someone configure it on the beta website so that we could test it?

**Comment by sergey-krusch** [comment]
@p12tic Thank you :) I was actually waiting for someone to confirm on the output format before doing the PR. But eventually discussion took a bit different route :)

**Comment by rasikapohankar** [comment]
@p12tic Can you please open a pull request with the new `output.txt`? It will be deployed to beta automatically for testing 🙂

**Comment by rasikapohankar** [comment]
I didn't mean to unassign @p12tic, not sure why it happened 😕 🤔 

@tagawa Can you please reassign @p12tic? I can't seem to find them in the list..

**Comment by tagawa** [comment]
@rasikapohankar Thanks for noticing. I think @p12tic has now removed himself from the contributor list so we can't assign it to him.

**Comment by p12tic** [comment]
Hmm, I did so because I was getting emails about all Fathead bugs. Perhaps I should look into muting threads instead next time.

**Comment by pjhampton** [comment]
Closing due to https://github.com/duckduckgo/zeroclickinfo-fathead/issues/781 👍
