### ISSUE TITLE
Java: Create category pages for class methods

### ISSUE THREAD

**Issue by marti1125** [duckduckgo/zeroclickinfo-fathead#491]
Here's an example of a category page for Ruby. 
https://duckduckgo.com/?q=ruby+array+methods&t=canonical&atb=v23&ia=list

**Comment by SuperHaker** [comment]
I would like to work on this.

**Comment by marti1125** [comment]
@moollaza could you give me extra information about this issue? please

**Comment by aegis2501** [comment]
@SuperHaker Hello. I'm currently working on the Java Fathead coverage and have noticed that the code I'm writing overlaps a lot with your assigned issue. since the only way you can test coverage for Java is by listing out all methods for all classes. Would you be interested in taking over my issue? Or the reverse? Alternatively, perhaps we could collaborate in order to avoid duplicate code.

**Comment by moollaza** [comment]
@aegis2501 your work does overlap somewhat, but I don't think @SuperHaker needs to take over for you, or vise versa.

The category pages is about providing the name of the category (or categories) that a given article should belong to.

This enables us to create category pages that list out all the related articles.

So for each article that is a class method, we can specify its "category" as "Java <class name> methods".

That way a search for "java classname methods" would show a tile view displaying all the articles we've put in that category. Just like we've done for Ruby.

The coverage you're working on won't really affect the categories because it doesn't test that. It tests that all the articles we expect to exist do actually exist in our output.txt file.

I hope this clarifies things?

**Comment by moollaza** [comment]
The work you're both doing can continue in parallel without issues.

**Comment by aegis2501** [comment]
I understand. Thank you for the clarification!

**Comment by pjhampton** [comment]
Hey @marti1125 

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
