### ISSUE TITLE
SASS: Remove extra newline above 'parameters'

### ISSUE THREAD

**Issue by hchienjo** [duckduckgo/zeroclickinfo-fathead#493]
There is an extra newline above 'parameters' subheading as can be seen for example, from here https://duckduckgo.com/?q=sass+opacify&t=lm&ia=about&iax=1

This needs to be removed.

------
IA Page:  http://duck.co/ia/view/sass 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @VeerpalBrar

**Comment by amarlearning** [comment]
@hchienjo I want to do this! :grin:

**Comment by hchienjo** [comment]
Just go ahead. Thanks @amarlearning for volunteering.

**Comment by amarlearning** [comment]
@hchienjo I think the Fathead template has a bug! This fathead script works fine!
See this : 
![screenshot from 2016-11-04 18-46-06](https://cloud.githubusercontent.com/assets/9383897/20006792/2d467b30-a2bf-11e6-8c7e-654575a644bb.png)
There is an extra `<br>` that is inserted before `Parameters`, because of which we can see an extra line!

It would be great if you tell me where can i find that template, so that i can fix it!

**Comment by hchienjo** [comment]
Unfortunately we can't edit the template, we'd need to make the parsing script remove the `<br>` or the extra line that is produced when the html parser encounters it.

You can refer to the [documentation](https://docs.duckduckhack.com/resources/fathead-overview.html) and also [join the forum](https://forum.duckduckhack.com/t/create-ia-sass-fathead/218) for more instructions and guidance.

You'd need to work on one of these two files: https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/lib/fathead/sass/parse_functions.py or https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/lib/fathead/sass/parse_reference.py, test it on codio and then submit a PR.

**Comment by amarlearning** [comment]
@hchienjo I'll find a way to do this!

**Comment by VeerpalBrar** [comment]
@amarlearning Thanks for taking this up! I would suggest starting with  https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/lib/fathead/sass/parse_functions.py file as it is the one responsible for parsing information about Sass functions and thus creates the parameter and example headings.

**Comment by amarlearning** [comment]
@VeerpalBrar This is strange at first when i looked at the code, I found a `<br>` tag due to which a line break was present!
But when i looked into the code today, there wasn't any `<br>` tag present! [screenshot]

![screenshot from 2016-11-10 22-03-21](https://cloud.githubusercontent.com/assets/9383897/20185376/d6d1ed02-a791-11e6-838e-7d632a43640b.png)

I think if somehow we can change the css properties of class `.prog__container`, we can resolve this issue 
![screenshot from 2016-11-10 22-07-38](https://cloud.githubusercontent.com/assets/9383897/20185520/628ad1e2-a792-11e6-9426-76aa6d011b06.png)

@VeerpalBrar As you are the maintainer, let me know what you think ?

**Comment by moollaza** [comment]
@hchienjo @amarlearning This is now fixed, we update the Fathead Database yesterday so that the code blocks have the newlines 👍

**Comment by moollaza** [comment]
Whoops, I thought this was the other issue. The `<br>` may have been from an older version of the output.txt -- The display looks correct to me now 👍
