### ISSUE TITLE
NodeJS Bug: not triggering for some articles

### ISSUE THREAD

**Issue by MariagraziaAlastra** [duckduckgo/zeroclickinfo-fathead#511]
### Description
A lot of the docs articles don't trigger. E.g. searching for "node dns lookupService", "node child disconnect", and "node http message service" don't show a NodeJS result. Investigate why.

## Steps to recreate
- [node dns lookupService](https://duckduckgo.com/?q=node+dns+lookupService&bext=msl&atb=v32-1__&ia=software)
- [node child disconnect](https://duckduckgo.com/?q=node+child+disconnect&bext=msl&atb=v32-1__&ia=web)
- [node http message service](https://duckduckgo.com/?q=node+http+message+service&bext=msl&atb=v32-1__&ia=qa)

## Get Started
- [x] 1) Claim this issue by commenting below
- [x] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/node_js

**Comment by No6things** [comment]
Couldn't recreate the bug, the search examples already show NodeJS result.
![image](https://cloud.githubusercontent.com/assets/7551968/20862143/685b4d06-b979-11e6-8dcb-d792041e1237.png)
![image](https://cloud.githubusercontent.com/assets/7551968/20862146/76980c4c-b979-11e6-8fef-
![image](https://cloud.githubusercontent.com/assets/7551968/20862147/7f9612da-b979-11e6-846c-df4c315e6d8e.png)
a61377a40fda.png)

**Comment by itai421** [comment]
I can take a look at this

**Comment by itai421** [comment]
This is what I did so far:

At first, I took a look at the "Steps to recreate":

- [node dns lookupService](https://duckduckgo.com/?q=node+dns+lookupService&bext=msl&atb=v32-1__&ia=software): did not triggered to [node dns.lookupService](https://duckduckgo.com/?q=node+dns.lookupService&bext=msl&atb=v32-1__&ia=software), but it did triggered both: [nodejs dns lookupService](https://duckduckgo.com/?q=nodejs+dns+lookupService&atb=v32-1__&ia=about) and [nodejs dns.lookupService](https://duckduckgo.com/?q=nodejs+dns.lookupService&atb=v32-1__&ia=aboutf)
 - [node child disconnect](https://duckduckgo.com/?q=node+child+disconnect&bext=msl&atb=v32-1__&ia=web) triggers for both: [childprocess.disconnect](https://duckduckgo.com/?q=childprocess.disconnect&atb=v32-1__&ia=about) and [childprocess disconnect](https://duckduckgo.com/?q=childprocess+disconnect&atb=v32-1__&ia=about)
 - [node http message service](https://duckduckgo.com/?q=node+http+message+service&bext=msl&atb=v32-1__&ia=qa) - I did not understand what should have been the result.


Than I tried to add a `redirects.txt` as mention at the [docs](https://docs.duckduckhack.com/programming-mission/creating-effective-fatheads.html) but when running it using `duckpan` it did not seem to work - even a test redirect `foo` to `childprocess.disconnect` did not do anything.

Honestly, I do not know what to do next, since I could not identify the problem, and I failed using the `redirects.txt` file, any ideas?

**Comment by pjhampton** [comment]
Hey @itai421,

Can you please push an early PR to create an ongoing to discourse?

**Comment by itai421** [comment]
Hey @pjhampton,
Unfortunately, I don't have anything to push, since, as mentioned in my comment, I did not know what to do...

**Comment by pjhampton** [comment]
Hey @itai421, 

Sorry for the late reply. The previous PRs have not improved the coverage for this Fathead. We need to create better redirects as Maria has pointed out. From my analysis of the unanswered query data, I have found that:

```
Triggers: node http.agent
Doesn't Trigger: node http agent

Triggers: node http
Doesn't Trigger: node http module

Triggers: nodejs crypto
Doesn't Trigger: node js crypto
```

The first two can be added as redirects in the `cover/redirects.txt` file, the third can be covered in `triggers.txt`. You can see an example here https://docs.duckduckhack.com/programming-mission/creating-effective-fatheads.html#using-a-redirectstxt-file

The duckpan server doesn't currently work with a redirects.txt file. The whole cover directory is ignored (as far as I know). The redirects.txt file is only useful in production.

**Comment by itai421** [comment]
O.K, good to know, I'll see what I can do

**Comment by itai421** [comment]
Do you want me to push work in progress?

**Comment by pjhampton** [comment]
Sure, sounds good!
