### ISSUE TITLE
Python: remove newline after the code block

### ISSUE THREAD

**Issue by MariagraziaAlastra** [duckduckgo/zeroclickinfo-fathead#524]
### Description
Remove newline after code blocks to save some space.
![4ff931ff6f7eec2a6a4a0bc7656e6ea9b2155009](https://cloud.githubusercontent.com/assets/3652195/19981210/643a6b4e-a1d7-11e6-93fe-dfea12da8919.jpg)

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/python

**Comment by Hestben** [comment]
This issue seems to be outdated. The current view of the search result is:
![python_unittest](https://cloud.githubusercontent.com/assets/22500915/20039081/5f94e38a-a43e-11e6-9425-62fc7f8e6cdf.png)

The page html code is`<section class=\"prog__container\"><p>Method called to prepare the test fixture. This is called immediately before calling the test method; other than AssertionError or SkipTest, any exception raised by this method will be considered an error rather than a test failure. The default implementation does nothing.</p><pre><code>setUp</code></pre></section>`

There are no extra line breaks, all the padding is in css.

**Comment by MariagraziaAlastra** [comment]
Thanks @Hestben! 
Yeah the data in production was outdated and I deployed the latest a couple days ago. Closing!
