### ISSUE TITLE
Python Requests Suggestion: Extend Parser and Add Coverage

### ISSUE THREAD

**Issue by pjhampton** [duckduckgo/zeroclickinfo-fathead#729]
## Description

It seems that this Fathead (Python Requests) just isn't triggering based on the following stats:

- Bounce Rate: 100%
- Engagement Rate: 0% 

This is a shame because there is a lot of people searching for requests related stuff. For example:

```
python requests hypermedia 
python requests irc 
python requests jsonrpc 
python requests limit page size time 
python requests oauth2 
python requests proxies 
python requests proxy 
python requests read 
python requests response headers 
python requests result filepointer 
python requests show headers 
python requests socks proxy 
python requests status_code 
python requests test url 
python requests ThreadPoolExecutor 
python requests tls streaming exception 
python requests tls streaming exception RST 
python requests unsupported browsers check 
python requests urljoin 
python requests utf8 
python requests write response 
python requests x-form-url-encoded 
python requests.get 
```

Further, I have noticed that:

Triggers: `JSON Response Content`
Doesn't Trigger: `requests JSON Response Content`

I think it would be helpful if we:

1. Scaled the existing parser to cover the [API docs](http://docs.python-requests.org/en/master/api/)

2. Added [coverage data](https://docs.duckduckhack.com/programming-mission/creating-effective-fatheads.html)

## People to notify
@hchienjo (Maintainer)
@duckduckgo/duckduckhack-contributors 

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/python_requests

**Comment by hchienjo** [comment]
I'll look into this.

**Comment by gautamkrishnar** [comment]
@hchienjo just assigned you agin... Its all yours :smile:

**Comment by hchienjo** [comment]
@pjhampton Is this issue partly escalated by the lack of a trigger word? I recall @moollaza was [concerned about triggering](https://github.com/duckduckgo/zeroclickinfo-fathead/pull/385#issuecomment-250499911). Then not so long afterwards, a [cheat sheet](https://duck.co/ia/view/requests_cheat_sheet) came along. Should we deprecate this fathead or we go ahead and improve it?

**Comment by pjhampton** [comment]
Hey @hchienjo! 👋 

The cheat sheet is awesome! But it's not really serving meeting the demands of the queries above. I think it would be good to take it forward, but I will leave it to @moollaza to make the final call 😄

**Comment by moollaza** [comment]
@pjhampton @hchienjo let's add a trigger-words.txt file -- that should allow it to trigger on queries like the ones above, assuming we have matching articles 👍 

A cheat sheet serves a different purpose and very specific query space, so they can't be compared. A cheat Sheet would never trigger for those queries because of how they work.

**Comment by hchienjo** [comment]
Hey @pjhampton @moollaza I have added the parsing of [http://docs.python-requests.org/en/master/api/](api docs) as well as added a trigger-words.txt. The problem is finding a source for cover data. What is the recommended way for looking for a source for cover data since in some modules, the official API docs are the only comprehensive source and this is not allowed to be taken as a source of cover data.

I have looked around and beautiful soup, Django and numpy don't have coverage data. I am not sure, but I suspect that finding a source that is as comprehensive as the official docs will be a problem.

What do you suggest?
