### ISSUE TITLE
C++: CPP Reference Fathead

### ISSUE THREAD

**Issue by pjhampton** [duckduckgo/zeroclickinfo-fathead#781]
# Recreate the CPP Reference Fathead Instant Answer
Help us make DuckDuckGo the best search engine for programmers!

### What do I need to know?
You'll need to know how to code in **Perl**, **Python**, **Ruby**, or **JavaScript**.
![fathead languages](https://cloud.githubusercontent.com/assets/873785/19787916/57b4c31a-9c73-11e6-9bd9-f85c8893ec93.jpg)

### What am I doing?
You will write a script that scrapes or downloads the data source below, and generates an **output.txt** file containing the parsed documentation. You can learn more about Fatheads and the `output.txt` syntax [**here**](https://docs.duckduckhack.com/resources/fathead-overview.html).

**Bonus Info** 🚀 : This Fathead already exists, and it's awesome! We have decided to make it a candidate for deprecation so we can align the code to mirror other Fatheads. Further, we don't wish to rely on external parties to provide the data. 

**Data source**: The same, but open to discussion.

**Instant Answer Page**: https://duck.co/ia/view/cppreference_doc

### What is the Goal?
As part of our [Programming Mission](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53), we're aiming to reach 100% Instant Answer (IA) coverage for searches related to programming languages by creating new Instant Answers, and improving existing ones.

Here are some Fathead examples:

- Ruby Docs
    - [Code](https://github.com/duckduckgo/zeroclickinfo-fathead/tree/master/lib/fathead/ruby) | [Example Query](https://duckduckgo.com/?q=array+bsearch&ia=about)
- MDN CSS
    - [Code](https://github.com/duckduckgo/zeroclickinfo-fathead/tree/master/lib/fathead/mdn_css) | [Example Query](https://duckduckgo.com/?q=css+background-position&ia=about)

  ![css background-position search](https://cloud.githubusercontent.com/assets/873785/19787980/cdf51566-9c73-11e6-9ef2-ac44dede62c7.png)

[See more related Instant Answers](https://duck.co/ia?repo=fathead)

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a new Instant Answer Page: https://duck.co/ia/new_ia (then let us know, here!)
- [ ] 5) Create the Fathead
- [ ] 6) Create a Pull Request
- [ ] 7) Ping @sahildua2305 for a review

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

**Comment by p12tic** [comment]
Note to whoever considers implementing this: the current implementation of cppreference_doc fathead is more than 1000 lines of python code - see https://github.com/p12tic/cppreference-doc/blob/master/index2ddg.py and its dependencies on the same repository. So any (re-)implementation of this will be either of similar complexity or lower quality, because the existing script relies on some manually updated metadata which would be very hard to recreate automatically. I'm not sure whether it's worth to spend effort on something that already works :-) I'm the author of the current fathead, so I might have some biases here, but the basic point should stand.

If the "relying on external parties to provide the data" is the main problem, this could be easily solved by making cppreference-doc repository a dependency and using it to fetch the data directly. On the other hand, the response time for requests from DuckDuckGo community so far has been no longer than a couple days, so there are probably few practical problems this change would solve. Again, I might be biased, just trying to bring some perspective :-)

**Comment by pjhampton** [comment]
We can close this for now
